<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Siswa;

class SiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $siswaData = [
            // Kelas 7
            [
                'nis' => '3122140369',
                'nama' => 'ANDI PURNAMA RAMADAN',
                'kelas' => '7',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2010-06-15',
                'status' => 'aktif',
            ],
            [
                'nis' => '0138963798',
                'nama' => 'AIS\'SYAH FITRIYANI NUR HASANAH',
                'kelas' => '7',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2010-08-20',
                'status' => 'aktif',
            ],
            [
                'nis' => '0130000001',
                'nama' => 'ARYA KASILA',
                'kelas' => '7',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2010-05-12',
                'status' => 'aktif',
            ],
            [
                'nis' => '3123976939',
                'nama' => 'AZIZAH NURMAWATI',
                'kelas' => '7',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2010-09-25',
                'status' => 'aktif',
            ],
            [
                'nis' => '0123668567',
                'nama' => 'EVAN RAMADHANI',
                'kelas' => '7',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2010-07-18',
                'status' => 'aktif',
            ],
            [
                'nis' => '3120446122',
                'nama' => 'FAISAL',
                'kelas' => '7',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2010-04-30',
                'status' => 'aktif',
            ],
            [
                'nis' => '3128234115',
                'nama' => 'IKHDINA HINDASYAH AZIZIAH',
                'kelas' => '7',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2010-11-10',
                'status' => 'aktif',
            ],
            [
                'nis' => '0127229425',
                'nama' => 'IWAN KURNIAWAN',
                'kelas' => '7',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2010-03-22',
                'status' => 'aktif',
            ],
            [
                'nis' => '0131409792',
                'nama' => 'LENI PITRIANI',
                'kelas' => '7',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2010-10-05',
                'status' => 'aktif',
            ],
            [
                'nis' => '3129018986',
                'nama' => 'MUHAMAD APRIANSYAH',
                'kelas' => '7',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2010-02-14',
                'status' => 'aktif',
            ],
            [
                'nis' => '0129160745',
                'nama' => 'RIAN SEPTIAN',
                'kelas' => '7',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2010-12-28',
                'status' => 'aktif',
            ],
            [
                'nis' => '0125994498',
                'nama' => 'TAUPIK ILYAS',
                'kelas' => '7',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2010-01-15',
                'status' => 'aktif',
            ],
            [
                'nis' => '0111220069',
                'nama' => 'WANDY ARIFIN',
                'kelas' => '7',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2010-08-08',
                'status' => 'aktif',
            ],
            // Kelas 8
            [
                'nis' => '0117130410',
                'nama' => 'ABDUL DIAN MAULANA',
                'kelas' => '8',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2011-10-06',
                'status' => 'aktif',
            ],
            [
                'nis' => '0119628141',
                'nama' => 'JAJANG NANA',
                'kelas' => '8',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2009-05-15',
                'status' => 'aktif',
            ],
            [
                'nis' => '0116220401',
                'nama' => 'MISYA KHOERUNNISYA',
                'kelas' => '8',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2009-08-20',
                'status' => 'aktif',
            ],
            [
                'nis' => '0115994284',
                'nama' => 'MUHAMAD IKRAM ABDUL MUGNI',
                'kelas' => '8',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2009-11-12',
                'status' => 'aktif',
            ],
            [
                'nis' => '0127772172',
                'nama' => 'RAFLA MUHAMAD JAENUR',
                'kelas' => '8',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2009-07-25',
                'status' => 'aktif',
            ],
            [
                'nis' => '0128267462',
                'nama' => 'RAFLI MUHAMAD JUHARI',
                'kelas' => '8',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2009-09-18',
                'status' => 'aktif',
            ],
            [
                'nis' => '3116811566',
                'nama' => 'SINTA AMELIA',
                'kelas' => '8',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2009-04-30',
                'status' => 'aktif',
            ],
            [
                'nis' => '0124133597',
                'nama' => 'SITI ALIFAH',
                'kelas' => '8',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2009-06-14',
                'status' => 'aktif',
            ],
            [
                'nis' => '3125593609',
                'nama' => 'YUDISTIRA',
                'kelas' => '8',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2009-03-22',
                'status' => 'aktif',
            ],
            [
                'nis' => '0113539217',
                'nama' => 'SENDY MAHARANI',
                'kelas' => '8',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2009-12-05',
                'status' => 'aktif',
            ],
            [
                'nis' => '0114979683',
                'nama' => 'NASYA MUTHIA RAMADANI',
                'kelas' => '8',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2009-10-28',
                'status' => 'aktif',
            ],
            // Kelas 9
            [
                'nis' => '121232110005230002',
                'nama' => 'AMELIA',
                'kelas' => '9',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2010-10-10',
                'status' => 'aktif',
            ],
            [
                'nis' => '121232110005230003',
                'nama' => 'AYAT NURLATIP',
                'kelas' => '9',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2010-04-26',
                'status' => 'aktif',
            ],
            [
                'nis' => '121232110005230004',
                'nama' => 'DEDE AHMAD NURDIANSYAH',
                'kelas' => '9',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2010-06-13',
                'status' => 'aktif',
            ],
            [
                'nis' => '121232110005240012',
                'nama' => 'FAJAR ROMADHON',
                'kelas' => '9',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2007-09-17',
                'status' => 'aktif',
            ],
            [
                'nis' => '121232110005240015',
                'nama' => 'LATIF AINUL YAKIM VARELA',
                'kelas' => '9',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2011-01-20',
                'status' => 'aktif',
            ],
            [
                'nis' => '121232110005230005',
                'nama' => 'DEWI KARTIKA',
                'kelas' => '9',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2008-11-25',
                'status' => 'aktif',
            ],
            [
                'nis' => '121232110005230006',
                'nama' => 'AHMAD FAUZI',
                'kelas' => '9',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2008-09-15',
                'status' => 'aktif',
            ],
            [
                'nis' => '121232110005230007',
                'nama' => 'SARI INDAH',
                'kelas' => '9',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2008-06-30',
                'status' => 'aktif',
            ],
            [
                'nis' => '121232110005230008',
                'nama' => 'BUDI SANTOSO',
                'kelas' => '9',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2008-05-12',
                'status' => 'aktif',
            ],
            [
                'nis' => '121232110005230009',
                'nama' => 'SITI NURHALIZA',
                'kelas' => '9',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2008-08-20',
                'status' => 'aktif',
            ],
            [
                'nis' => '121232110005230010',
                'nama' => 'JOKO SUSILO',
                'kelas' => '9',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2008-03-25',
                'status' => 'aktif',
            ],
            [
                'nis' => '121232110005230011',
                'nama' => 'RINA WULANDARI',
                'kelas' => '9',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2008-07-18',
                'status' => 'aktif',
            ],
            [
                'nis' => '121232110005230012',
                'nama' => 'ANDI PRASETYA',
                'kelas' => '9',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2008-12-05',
                'status' => 'aktif',
            ],
            [
                'nis' => '121232110005230013',
                'nama' => 'MELATI SARI',
                'kelas' => '9',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2008-04-14',
                'status' => 'aktif',
            ],
            [
                'nis' => '121232110005230014',
                'nama' => 'RIZKI RAMADHAN',
                'kelas' => '9',
                'jenis_kelamin' => 'Laki-laki',
                'tanggal_lahir' => '2008-02-28',
                'status' => 'aktif',
            ],
            [
                'nis' => '121232110005230015',
                'nama' => 'PUTRI AYU',
                'kelas' => '9',
                'jenis_kelamin' => 'Perempuan',
                'tanggal_lahir' => '2008-10-30',
                'status' => 'aktif',
            ],
        ];

        foreach ($siswaData as $data) {
            Siswa::updateOrCreate(
                ['nis' => $data['nis']],
                $data
            );
        }
    }
}
